# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "assembleRelease")
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do
    gradle(task: "clean assembleRelease")
    
    firebase_app_distribution(
      app: "1:686188358517:android:2a56d6d01726b02525013c",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      apk_path: "app/build/outputs/apk/release/app-release.apk",
      release_notes: "Bản build mới từ Fastlane",
      debug: true
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
